### ISSUE TITLE
Error in running STARK

### ISSUE THREAD

**Issue by Nour-EddineS** [bioinfo-chru-strasbourg/STARK#4]
Dear all,

I tried to run : 
**docker exec -ti stark-module-stark-submodule-stark-service-cli bash**
but I got this error:
**Error: No such container: stark-module-stark-submodule-stark-service-cli**

Does anybody have an idea please ?
Thank you in advance

**Comment by antonylebechec** [comment]
Dear Nour,

First of all, we just updated STARK release (0.9.18.4). Master branch is now up-to-date.

Can you provide more information about your system? (OS, docker release...).

Moreover, did you use "quick install" procedure ("Getting started" section) or the more complete install procedure?

## Install

Once download step is done (`git` command), the building step (`docker-compose build` command) should create main STARK docker image. What is the command output?

To check the correct build of the image, you can run this command:
```
docker images | grep "stark"
```
You should have this kind of output:
```
stark/stark-sources                   0.9.18.4           e94e10b17292   7 weeks ago     3.96GB
```

## Services

STARK main services (CLI, API...) are based on main STARK docker image (currently "stark/stark-sources:0.9.18.4"). By running the STARK services command (`services/services.sh --modules=* --command=up`), you should have docker services running. What is the command output? (use option `--verbose` for more information).

To check if services are running, you can run this command:
```
docker ps | grep "stark-module-stark"
```

You should have this kind of output:
```
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS         PORTS     NAMES
1444557333f2   stark/stark:0.9.18.4     "/bin/bash -c 'while…"   44 seconds ago   Up 43 seconds            stark-module-stark-submodule-stark-service-cli
```

Your error message suggests that STARK service "stark-module-stark-submodule-stark-service-cli" was not correctly launched by the STARK services command.

Feel free to contact us!

**Comment by Nour-EddineS** [comment]
Dear  @antonylebechec,
hank you for your reply.
I found out that the problem comes from the Build step i.e. the cmd "docker-compose build" was not solved successfully. Look at the error details in the "setupe.log" file. Do you have any idea how to solve this problem.
I have this problem with both installation methods (Getting Started & Complete setup).
Almost a week ago I tried with the same problem, thanks for your suggestions.

**My OS:**

No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 20.04.5 LTS
Release: 20.04
Codename: focal

  **My docker Version:**

Customer:
  Version: 20.10.12
  API version: 1.41
  Go version: go1.16.2
  Git commit: 20.10.12-0ubuntu2~20.04.1
  Built: Wed Apr 6 02:14:38 2022
  OS/Arch: linux/amd64
  Context: default
  Experimental: true

server:
  Engine:
   Version: 20.10.17
   API version: 1.41 (minimum version 1.12)
   Go version: go1.18.5
   Git commit: a89b842
   Built: Mon Oct 17 06:20:42 2022
   OS/Arch: linux/amd64
   Experimental: false
  containerd:
   Version: v1.6.6
   GitCommit: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
  runc:
   Version: 1.1.2
   GitCommit:
  docker-init:
   Version: 0.19.0
[setup.log](https://github.com/bioinfo-chru-strasbourg/STARK/files/10430209/setup.log)

   GitCommit: de40ad0

Thank you in advance!

**Comment by antonylebechec** [comment]
Dear Nour-Eddine,

It seems that Python2 module installation step failed. Especially, the connexion to download server failed ("Failed to establish a new connection").

Do you have a proxy? 

Moreover, "Python 2.7 reached the end of its life on January 1st, 2020". We'll probably remove Python 2.7 in future release of STARK, due to this obsolescence. This will remove some features like caller (e.g. MuTect:1.1.7).

**Comment by Nour-EddineS** [comment]
Dear @antonylebechec,

After setting the connexion, the command **"docker-compose"** is solved successfully. But when i run **"sudo services/services.sh --modules=* --command=up"**: i got the same issue #5. 

According to your proposal I must do this if only if I have ''docker compose", but i don't have "docker compose" on my docker version, that's what I have "docker-compose"!
So if I understand correctly I have to change the docker version which contains "docker compose" and not "docker-compose"?

The version i have:

$ docker-compose version

/snap/docker/2343/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
from cryptography.hazmat.backends import default_backend
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.6.9
OpenSSL version: OpenSSL 1.1.1 11 Sep 2018

Sincerely,

**Comment by VironicaZ** [comment]
Yes, the same thing is happening to me !

**Comment by antonylebechec** [comment]
Dear Nour-Eddine, Vironica,

Thank a lot for your feedback!

As the proxy issue is solved, I close it (and rename it to specify the problem). Let's switch to #5 issue then.
