### ISSUE TITLE
Improve RAM usage for demanding rules

### ISSUE THREAD

**Issue by SamuelNicaise** [bioinfo-chru-strasbourg/STARK#8]
Some rules, e.g. STAR alignement (under development) or CollectHsMetrics require a lot more RAM per sample than what is currently attributed. This causes STARK to crash when using those rules with very large samples.

Suggested solution: implement a way to limit concurrent rule execution, allowing to give those rules more RAM

**Comment by antonylebechec** [comment]
Fix in PR #22
